DROP TABLE DB2INST1.ACCOUNTS; 
CREATE TABLE DB2INST1.ACCOUNTS ( 
    ACCOUNTID VARCHAR (50)  NOT NULL , 
    PASSWORD VARCHAR (50) , 
    MANAGER VARCHAR (50) , 
    MIDDLENAME VARCHAR (50) , 
    FIRSTNAME VARCHAR (50) NOT NULL ,
    LASTNAME VARCHAR (50) NOT NULL , 
    EMAIL VARCHAR (250) , 
    DEPARTMENT VARCHAR (250) ,
    TITLE VARCHAR (250) , 
    AGE INTEGER , 
    SALARY DECIMAL (7, 2) , 
    JPEGPHOTO BLOB  (1 M )   LOGGED  NOT  COMPACT ,
    CONSTRAINT CC1224509213217 PRIMARY KEY ( ACCOUNTID)  
);