DROP TABLE "ACCOUNTS";
CREATE TABLE  "ACCOUNTS" ( 
    "ACCOUNTID" VARCHAR2(50) NOT NULL,  
    "PASSWORD" VARCHAR2(50), 
    "MANAGER" VARCHAR2(50), 
    "MIDDLENAME" VARCHAR2(50), 
    "FIRSTNAME" VARCHAR2(50) NOT NULL, 
    "LASTNAME" VARCHAR2(50) NOT NULL, 
    "EMAIL" VARCHAR2(250), 
    "DEPARTMENT" VARCHAR2(250), 
    "TITLE" VARCHAR2(250), 
    "AGE" INTEGER,
    "SALARY" NUMBER(9,2), 
    "JPEGPHOTO" BLOB, 
    PRIMARY KEY ("ACCOUNTID") ENABLE
);
DROP TABLE "BUG17551";
CREATE TABLE "BUG17551" (
    "ACCOUNTID" VARCHAR2(50) NOT NULL,  
    "PASSWORD" VARCHAR2(50), 
    "EMAIL" VARCHAR2(250), 
    "TMS" TIMESTAMP
);