DROP TABLE  "ACCOUNTS"; 
CREATE TABLE  "ACCOUNTS" 
   ( "ACCOUNTID" VARCHAR(50), 
    "PASSWORD" VARCHAR(50), 
    "MANAGER" VARCHAR(50) NULL, 
    "MIDDLENAME" VARCHAR(50) NULL, 
    "FIRSTNAME" VARCHAR(50) NOT NULL, 
    "LASTNAME" VARCHAR(50) NOT NULL, 
    "EMAIL" VARCHAR(250) NULL, 
    "DEPARTMENT" VARCHAR(250) NULL, 
    "TITLE" VARCHAR(250) NULL, 
    "AGE" INTEGER NULL, 
    "SALARY" DECIMAL(9,2) NULL, 
    "JPEGPHOTO" VARBINARY(8000) NULL,
    "CHANGELOG" TIMESTAMP,
     PRIMARY KEY ("ACCOUNTID") 
   );
